version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: emage-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend-node
    container_name: emage-backend
    restart: always
    env_file:
      - ./backend-node/.env
    depends_on:
      - mongo
      - cpp-service
    ports:
      - "8080:8080"
      
  frontend:
    build: ./frontend
    container_name: emage-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080

  cpp-service:
    build: ./cpp-service
    container_name: emage-cpp
    restart: always
    ports:
      - "8000:8000"

volumes:
  mongo_data:
