version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: emage-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend-node
    container_name: emage-backend
    restart: always
    env_file:
      - ./backend-node/.env.docker
    depends_on:
      - mongo
      - cpp-service
    volumes:
      - uploads_data:/app/uploads

  cpp-service:
    build: ./cpp-service
    container_name: emage-cpp
    restart: always

  frontend:
    build: ./frontend
    container_name: emage-frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.docker

  nginx:
    image: nginx:alpine
    container_name: emage-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
  uploads_data:
